name: Push 

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted

        steps:
          - name: Deploy on server 1 
            env: 
              SSH_KEY: ${{secrets.SSH_KEY}}
              SERVER_HOST2: ${{secrets.SERVER_HOST2}}
              SSH_USER: ${{secrets.SSH_USER}}
            run: |
                echo "$SSH_KEY" > ssh_key.pem
                chmod 600 ssh_key.pem
                ssh -i ssh_key.pem $SSH_USER@$SERVER_HOST2 "cd /docker-compose-flask-app && git pull https://github.com/faialotaibi/docker-compose-flask-app.git && docker compose up -d --build"